### ISSUE TITLE
Publish request to crates.io

### ISSUE THREAD

**Issue by N0fix** [google/authenticode-rs#97]
Quite a lot of fixes have been done since `0.3.0`, some of them allowing me to catch errors in authenticode parsing, others are fixing bugs, thanks for it.

However, crates.io prevents from publishing crates that relies on git repositories as versions in their dependencies, e.g: 
```
[dependencies]
authenticode = { git = "https://github.com/google/authenticode-rs.git" } # Fixes a lot of stuff since "0.3.0"
```
Could you please publish the current - or recent - version of the project to crates.io?

Have a great day !

**Comment by nicholasbishop** [comment]
Thanks for the reminder, published [0.4.0](https://crates.io/crates/authenticode/0.4.0)
